name: Deploy Landing to OCI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to OCI Object Storage
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_USER_OCID }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_TENANCY_OCID }}
          OCI_CLI_REGION:      ${{ secrets.OCI_REGION }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_FILE }}
        with:
          command: >
            os object bulk-upload
            -bn petlandia-clubhouse
            --src-dir ./
            --exclude ".git/*"
            --exclude "README.md"
            --overwrite